### ISSUE TITLE
Update pypi release

### ISSUE THREAD

**Issue by dirkmoors** [vikingco/django-states2#64]
Hi :)

Could you create a new pypi release (version update) for django-states2 (master)? At VikingCo that is the current version we're working with, and since it is stable, it would be preferable to have a tag with a new pypi release.

Thanks in advance

**Comment by jonathanslenders** [comment]
I made @jgeskens also owner of django-states2, can you ask him to publish a new version to Pypi?
Maybe also have a look at  https://github.com/vikingco/django-states2/pull/65

Jonathan

**Comment by jpadilla** [comment]
@jonathanslenders thanks.

**Comment by dirkmoors** [comment]
Thanks @jonathanslenders, I'll talk to Jef about it!

**Comment by jgeskens** [comment]
I merged #65 and released the current master as 1.6.4: https://pypi.python.org/pypi/django-states

**Comment by nicktimko** [comment]
PyPI is lagging at 1.6.5 while 1.6.8 is tagged on GitHub. Installing from locations other than PyPI is generally a miserable process; can you add a build & publish to your tagging procedure?
